language: java

jdk:
  - openjdk8

branches:
  only:
    - master
    - development

env:
  global:
    secure: 6va3SCR8GWGyjZ8Rg4iRZrptrLKBa1z+vFBWIjlVYJXnI+zmh9hUA3R5HVxQbMVXLZ8AL8QTXeQt6ivqCb+bPVsNMzRyuO+W6Lw5xv/kmX8kg0BXzlT0x9Pe99vclEr9bpV+hpMYNqjD+q00ppi3ziApgsBsxNwOMY3bOEA6IPJFPb7ZLnOaD8vbsv//9aqooEuaC9vFDHi3fx7ypyUGz0oLqwc1vRUbNrvNd2/+JTsY+sJmVAdomyyVdcIkZoBCrudKAQ1LjEplf66F1aGJtkCTa/y0RH2GJQrEvkxRlnudmq59rH0et4biyxXw8daOeRsAT5jgLbY8WlUeTp15ULExW3+E0wIi9OK8PJXY5KlD7yqANCZ0yaomafx+ZXGGHdwz8XYFpO4sjsdIUwWX7OTIcNhe5QvSKIFDOKDLO17hH9PeUcywkvFtVMd8bCT350JBWrK2P1WdJnmD+uVHx/1LAW2uepF7JghiBj5vTm9oFmqPoEZKacCACRV67ESS1syJsdJCWSB6d98t3W4cXAVRmgKBGftY+3KIT42JXkKzj9Kgvvv0elCh5wXaKCD/9bWmRYZpcmTJXuBEeFGwLvrz0M2V/ZdvIa1ExWIc+NzPWhsEAnly9N2Qo0ErFCSJxfxo7+netB3Xixjxfqp+AOiq89mBV6eSJg80cR0gueA=


before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
  - echo $project_version

deploy:
  provider: releases
  api_key:
    secure: nn5LNw6hId7n9aHfwnfjvc6nj3gezjlNCa2qtg/ryptmWKILOs4I+eHinvM8Db4BqUCgoYFGoLDEMg25b0Z5uQCfnwDcpB7mDmVEZIdkRBZEW3otrgizgZ0rcnQ4022EsO/Xe515C1Ao7AgTDWzedsgs8c50+Cw8ajFRZcCu3BUQdesVPAgmGKgHoPw5CW+Tz2bVteFQXIVNkImFeCiMRT23HpQd2EP9lqj2xBw7hv3TUERXU6az9KtFXe1ZQrnaQfTAW4/GTm9OGUeoP2Ab+442zuCxrWF4jGxqCDWADFOBl5+vmBKy0w0ebl4foO+mfhIMlBlY0+Jmv1Oo4RYGFC2RWPqZyEmeJNudyy05LXAK/tGqpgf6K+ic6U8pNJOa6DzVkyQ13dIO9kRCE+yPJ68eE9YXXF0497Qb8KQCl3Bltlb6K5XlMmM6FBu6228Lq7RZYha1aeeBmxbRb15AN+QtxYbbEFTEUfaQODMlEk2kzcaimdWDAcVK0JEx0hm+7tDG+jT7jiXr6IPrs4EXJsZG9A5XVejA/lmqkqcpkruYDnEtaffzOK9rcuxKdrSaJ4ErJ1M7vgwXfeCbmyEFm+sXBwVfxwsciwcjiTm8JemsWwTkhaUzUMFigmIw2R4qvcBgJs1mfsgKRK4uxMBqh/puqh/47e0+OaSsWFI35NQ=
  skip_cleanup: true
  file: dacdoc-maven-plugin/target/dacdoc-maven-plugin-$project_version.jar
  on:
    repo: flussig/dacdoc
    branch: master
    tags: true
  name: $project_version

install:
  - if [ ! $TRAVIS_PULL_REQUEST == false ];
    then echo "build and test"; mvn --settings .maven.xml install -Dgpg.skip -Dmaven.javadoc.skip=true -B -V;
    else echo "no build and test for non-PR";
    fi


## Build and release to maven central
script:
  - if [ $TRAVIS_PULL_REQUEST == false ] && [ $TRAVIS_BRANCH == "master" ];
    then echo "release to maven central"; mvn release:clean release:prepare release:perform --settings .maven.xml -DskipTests=true -B -U -Prelease;
    else echo "no release to maven for PR or non-master branches";
    fi
