language: java

jdk:
  - openjdk8

branches:
  only:
    - gh-pages-development

env:
  global:
    secure: 6va3SCR8GWGyjZ8Rg4iRZrptrLKBa1z+vFBWIjlVYJXnI+zmh9hUA3R5HVxQbMVXLZ8AL8QTXeQt6ivqCb+bPVsNMzRyuO+W6Lw5xv/kmX8kg0BXzlT0x9Pe99vclEr9bpV+hpMYNqjD+q00ppi3ziApgsBsxNwOMY3bOEA6IPJFPb7ZLnOaD8vbsv//9aqooEuaC9vFDHi3fx7ypyUGz0oLqwc1vRUbNrvNd2/+JTsY+sJmVAdomyyVdcIkZoBCrudKAQ1LjEplf66F1aGJtkCTa/y0RH2GJQrEvkxRlnudmq59rH0et4biyxXw8daOeRsAT5jgLbY8WlUeTp15ULExW3+E0wIi9OK8PJXY5KlD7yqANCZ0yaomafx+ZXGGHdwz8XYFpO4sjsdIUwWX7OTIcNhe5QvSKIFDOKDLO17hH9PeUcywkvFtVMd8bCT350JBWrK2P1WdJnmD+uVHx/1LAW2uepF7JghiBj5vTm9oFmqPoEZKacCACRV67ESS1syJsdJCWSB6d98t3W4cXAVRmgKBGftY+3KIT42JXkKzj9Kgvvv0elCh5wXaKCD/9bWmRYZpcmTJXuBEeFGwLvrz0M2V/ZdvIa1ExWIc+NzPWhsEAnly9N2Qo0ErFCSJxfxo7+netB3Xixjxfqp+AOiq89mBV6eSJg80cR0gueA=


before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

